apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: thor
  #namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: thor
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 10