apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ printf "dll-%s-sc" (include "hpcc-azuredisk.fullname" $) }}
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: {{ .Values.dllStorage.sku | default "Standard_LRS" }}
reclaimPolicy: Retain
allowVolumeExpansion: true
